CREATE TABLE `materials` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`materialId` varchar(32) NOT NULL,
	`materialType` enum('Surface','Medium','Tool') NOT NULL,
	`displayName` varchar(100) NOT NULL,
	`aliases` json,
	`firstUsedDate` timestamp,
	`notes` varchar(200),
	`usedInWorksCount` int NOT NULL DEFAULT 0,
	`reactivityProfile` enum('Stable','Responsive','Volatile','Chaotic'),
	`edgeBehavior` enum('Sharp','Feathered','Blooming','Fractured'),
	`absorptionCurve` enum('Immediate','Delayed','Variable'),
	`consistencyPattern` enum('Reliable','Variable','Glitch_Prone'),
	`practiceRole` enum('Final_Work','Exploration','Anxiety_Discharge','Conditioning'),
	`viscosityBand` enum('Thin','Balanced','Dense'),
	`chromaticForce` enum('Muted','Balanced','Aggressive'),
	`reactivationTendency` enum('Low','Medium','High'),
	`forgivenessWindow` enum('Narrow','Medium','Wide'),
	`dilutionSensitivity` enum('Low','Medium','High'),
	`sedimentationBehavior` enum('Stable','Variable'),
	`contactMode` enum('Direct','Indirect','Mediated','Mechanical'),
	`controlBias` enum('Precision','Balanced','Chaos'),
	`repeatability` enum('High','Medium','Low'),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `materials_id` PRIMARY KEY(`id`),
	CONSTRAINT `materials_materialId_unique` UNIQUE(`materialId`)
);
--> statement-breakpoint
CREATE TABLE `works_core` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`code` varchar(16) NOT NULL,
	`date` timestamp NOT NULL,
	`surfaceId` int NOT NULL,
	`mediumId` int NOT NULL,
	`toolId` int,
	`technicalIntent` varchar(140),
	`discovery` varchar(280),
	`rating` int NOT NULL,
	`disposition` enum('Trash','Probably_Trash','Save') NOT NULL,
	`photoUrl` text,
	`photoKey` varchar(256),
	`sessionId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `works_core_id` PRIMARY KEY(`id`),
	CONSTRAINT `works_core_code_unique` UNIQUE(`code`)
);
